### ISSUE TITLE
Next-Payload not working together with plugin-seo

### ISSUE THREAD

**Issue by rpfaeffle** [payloadcms/plugin-seo#40] opened 2023-03-04 09:49 UTC
When trying to work with `next-payload`, one can currently not use `plugin-seo`. It took me some time to figure out why the login screen was not loading. But after some debugging I found out it is due to `plugin-seo`.

When deploying to vercel, with `plugin-seo` enabled, one gets the following runtime error for `/api/users/me` and `/api/users/init`:

```
/var/task/apps/payload/node_modules/payload/dist/admin/components/forms/Label/index.scss:1
@import '../../../scss/styles.scss';
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1094:15)
    at Module._compile (node:internal/modules/cjs/loader:1129:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/task/apps/payload/node_modules/payload/dist/admin/components/forms/Label/index.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
```

Locally everything works without issues.

**Comment by onepoordeveloper** [comment] 2023-03-15 11:38
@rpfaeffle I'm facing this also on my localhost. Did you find a solution?

**Comment by rpfaeffle** [comment] 2023-03-15 15:54
Hey @onepoordeveloper,

my currrent workaround is adding the fields manually without the features provided by the plugin.

**Comment by jacobsfletch** [comment] 2023-05-16 02:47
@JarrodMFlesch do you have any idea what might be going on here? Would https://github.com/payloadcms/plugin-seo/pull/45 fix this?

**Comment by onepoordeveloper** [comment] 2023-05-28 12:28
any update on this plz?

**Comment by jacobsfletch** [comment] 2023-06-02 14:19
Hey @rpfaeffle and @onepoordeveloper, it looks like that error is because the plugin imports a React component that uses scss and the compiler does not recognize the syntax. Do either of you have `sass` installed in your Next.js app? I believe Next.js natively supports it, so all you have to is run `yarn add sass` or `npm i --save sass` and no additional setup is needed. Give that a try and let me know if the error persists!

**Comment by rpfaeffle** [comment] 2023-06-02 15:23
Hey @jacobsfletch,

I do have `sass` as well as `sass-loader` installed in my Next.js app. Do you think this might be related to the fact that I am using `pnpm` as my package manager?

**Comment by onepoordeveloper** [comment] 2023-06-02 19:22
@jacobsfletch thank you for the response.

I had `sass` in my project. I realized that it is not needed so I
1. removed it from `package.json`
2. removed node_modules directory
3. removed package-lock.json
4. ran `npm i`
5. and `npm run dev`

and the error still persists..

**Comment by onepoordeveloper** [comment] 2023-07-11 07:46
@jacobsfletch I noticed the same error appears when I am using `@payloadcms/plugin-form-builder`

This is my configuration, results are same if I keep everything to default like `formBuilder({})`.

![image](https://github.com/payloadcms/plugin-seo/assets/11477731/d9cf9d98-ef19-4b58-a0f1-ba1a70e7ba53)

```
@import '../../../scss/styles.scss';
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ahmad/projects/f44/yungo/node_modules/payload/dist/admin/components/forms/Label/index.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ahmad/projects/f44/yungo/node_modules/payload/dist/admin/components/forms/field-types/Text/Input.js:8:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ahmad/projects/f44/yungo/node_modules/payload/dist/admin/components/forms/field-types/Text/index.js:33:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ahmad/projects/f44/yungo/node_modules/payload/components/forms.js:27:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ahmad/projects/f44/yungo/node_modules/@payloadcms/plugin-form-builder/dist/collections/Forms/DynamicFieldSelector.js:40:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ahmad/projects/f44/yungo/node_modules/@payloadcms/plugin-form-builder/dist/collections/Forms/fields.js:15:30)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  page: '/'
}
```

**Comment by onepoordeveloper** [comment] 2023-07-13 07:25
Ok, so based on my discussion at Payload's official discord (https://discord.com/channels/967097582721572934/1128234019012743241) this can be resolved by following the below steps

1. use `withPayload`
2. add the problematic plugin `@payloadcms/plugin-seo` in transpilePackages
3. boom

```
  transpilePackages: ['@react-three/postprocessing', '@payloadcms/plugin-form-builder', '@payloadcms/plugin-seo'],
```

**Closed** 2023-07-13 13:35 UTC

**Comment by cbratschi** [comment] 2023-08-14 20:09
I am getting the same Sass build issue but I am using Payload independently of Next.js. It happens as soon as the SEO plugin is used. How can I fix this case?

**Comment by onepoordeveloper** [comment] 2023-08-15 07:53
@cbratschi 

I was facing the exact same issue and you can use [my last comment above](https://github.com/payloadcms/plugin-seo/issues/40#issuecomment-1633708764) as a guide on how I fixed it.

**Comment by cbratschi** [comment] 2023-08-15 09:49
@onepoordeveloper I am using Payload directly not through Next.js. Therefore your workaround does not apply. It's failing in this case in dev mode and also as transpiled TypeScript.

I think the problem is a different one: some client code processed through Webpack is referenced by the SEO plugin and gets used in backend code. In this case Webpack Sass is not supported.
